version: '3'
services:
  # Self-hosted docker registry
  docker-registry:
    container_name: docker-registry
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
            - ./volume:/var/lib/registry
  # Gui for Self-hosted docker registry
  docker-registry-ui:
    container_name: docker-registry-ui
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: always
    network_mode: host
    volumes:
      - './prometheus.yml/etc/prometheus/prometheus.yml'
  # Grafana for visualization
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana
    restart: always
    network_mode: host
    depends_on:
      - prometheus
    volumes:
      - './grafana.ini/etc/grafana/grafana.ini'
